// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: alt_pt.proto

package proto_alt_pt

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DisabilityInfo_Type int32

const (
	DisabilityInfo_BREAK_DOWN DisabilityInfo_Type = 0 // 故障
	DisabilityInfo_ACCIDENT   DisabilityInfo_Type = 1 // 事故
	DisabilityInfo_DISASTER   DisabilityInfo_Type = 2 // 自然災害
)

// Enum value maps for DisabilityInfo_Type.
var (
	DisabilityInfo_Type_name = map[int32]string{
		0: "BREAK_DOWN",
		1: "ACCIDENT",
		2: "DISASTER",
	}
	DisabilityInfo_Type_value = map[string]int32{
		"BREAK_DOWN": 0,
		"ACCIDENT":   1,
		"DISASTER":   2,
	}
)

func (x DisabilityInfo_Type) Enum() *DisabilityInfo_Type {
	p := new(DisabilityInfo_Type)
	*p = x
	return p
}

func (x DisabilityInfo_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisabilityInfo_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_alt_pt_proto_enumTypes[0].Descriptor()
}

func (DisabilityInfo_Type) Type() protoreflect.EnumType {
	return &file_alt_pt_proto_enumTypes[0]
}

func (x DisabilityInfo_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisabilityInfo_Type.Descriptor instead.
func (DisabilityInfo_Type) EnumDescriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{1, 0}
}

type DisabilityResponse_Result int32

const (
	DisabilityResponse_SUCCESS DisabilityResponse_Result = 0 // 成功
	DisabilityResponse_FAILURE DisabilityResponse_Result = 1 // 失敗
)

// Enum value maps for DisabilityResponse_Result.
var (
	DisabilityResponse_Result_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	DisabilityResponse_Result_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x DisabilityResponse_Result) Enum() *DisabilityResponse_Result {
	p := new(DisabilityResponse_Result)
	*p = x
	return p
}

func (x DisabilityResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisabilityResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_alt_pt_proto_enumTypes[1].Descriptor()
}

func (DisabilityResponse_Result) Type() protoreflect.EnumType {
	return &file_alt_pt_proto_enumTypes[1]
}

func (x DisabilityResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisabilityResponse_Result.Descriptor instead.
func (DisabilityResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{2, 0}
}

type DispatchResponse_Result int32

const (
	DispatchResponse_SUCCESS DispatchResponse_Result = 0 // 配車完了
	DispatchResponse_FAILURE DispatchResponse_Result = 1 // 配車失敗
)

// Enum value maps for DispatchResponse_Result.
var (
	DispatchResponse_Result_name = map[int32]string{
		0: "SUCCESS",
		1: "FAILURE",
	}
	DispatchResponse_Result_value = map[string]int32{
		"SUCCESS": 0,
		"FAILURE": 1,
	}
)

func (x DispatchResponse_Result) Enum() *DispatchResponse_Result {
	p := new(DispatchResponse_Result)
	*p = x
	return p
}

func (x DispatchResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DispatchResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_alt_pt_proto_enumTypes[2].Descriptor()
}

func (DispatchResponse_Result) Type() protoreflect.EnumType {
	return &file_alt_pt_proto_enumTypes[2]
}

func (x DispatchResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DispatchResponse_Result.Descriptor instead.
func (DispatchResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{4, 0}
}

type VehicleStatusRequest_Status int32

const (
	VehicleStatusRequest_READY   VehicleStatusRequest_Status = 0 // 待機中 (経路未割当)
	VehicleStatusRequest_RUNNING VehicleStatusRequest_Status = 1 // 走行中 (経路割当済)
)

// Enum value maps for VehicleStatusRequest_Status.
var (
	VehicleStatusRequest_Status_name = map[int32]string{
		0: "READY",
		1: "RUNNING",
	}
	VehicleStatusRequest_Status_value = map[string]int32{
		"READY":   0,
		"RUNNING": 1,
	}
)

func (x VehicleStatusRequest_Status) Enum() *VehicleStatusRequest_Status {
	p := new(VehicleStatusRequest_Status)
	*p = x
	return p
}

func (x VehicleStatusRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatusRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_alt_pt_proto_enumTypes[3].Descriptor()
}

func (VehicleStatusRequest_Status) Type() protoreflect.EnumType {
	return &file_alt_pt_proto_enumTypes[3]
}

func (x VehicleStatusRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatusRequest_Status.Descriptor instead.
func (VehicleStatusRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{7, 0}
}

type VehicleStatusResponse_Result int32

const (
	VehicleStatusResponse_COMPLETED VehicleStatusResponse_Result = 0
	VehicleStatusResponse_WATING    VehicleStatusResponse_Result = 1
)

// Enum value maps for VehicleStatusResponse_Result.
var (
	VehicleStatusResponse_Result_name = map[int32]string{
		0: "COMPLETED",
		1: "WATING",
	}
	VehicleStatusResponse_Result_value = map[string]int32{
		"COMPLETED": 0,
		"WATING":    1,
	}
)

func (x VehicleStatusResponse_Result) Enum() *VehicleStatusResponse_Result {
	p := new(VehicleStatusResponse_Result)
	*p = x
	return p
}

func (x VehicleStatusResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleStatusResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_alt_pt_proto_enumTypes[4].Descriptor()
}

func (VehicleStatusResponse_Result) Type() protoreflect.EnumType {
	return &file_alt_pt_proto_enumTypes[4]
}

func (x VehicleStatusResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleStatusResponse_Result.Descriptor instead.
func (VehicleStatusResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{8, 0}
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"` // 緯度 (EPSG:3857)
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"` // 経度 (EPSG:3857)
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Point) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

// 障害情報 (通知)
type DisabilityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // 発生時刻
	Type      DisabilityInfo_Type    `protobuf:"varint,2,opt,name=type,proto3,enum=proto.alt_pt.DisabilityInfo_Type" json:"type,omitempty"` // 障害種別
	Point     *Point                 `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`                                      // 発生場所
}

func (x *DisabilityInfo) Reset() {
	*x = DisabilityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisabilityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabilityInfo) ProtoMessage() {}

func (x *DisabilityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabilityInfo.ProtoReflect.Descriptor instead.
func (*DisabilityInfo) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{1}
}

func (x *DisabilityInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DisabilityInfo) GetType() DisabilityInfo_Type {
	if x != nil {
		return x.Type
	}
	return DisabilityInfo_BREAK_DOWN
}

func (x *DisabilityInfo) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

// 障害情報 (応答)
type DisabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                        // 応答時刻
	Result    DisabilityResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=proto.alt_pt.DisabilityResponse_Result" json:"result,omitempty"` // 結果
}

func (x *DisabilityResponse) Reset() {
	*x = DisabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisabilityResponse) ProtoMessage() {}

func (x *DisabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisabilityResponse.ProtoReflect.Descriptor instead.
func (*DisabilityResponse) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{2}
}

func (x *DisabilityResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DisabilityResponse) GetResult() DisabilityResponse_Result {
	if x != nil {
		return x.Result
	}
	return DisabilityResponse_SUCCESS
}

// Dispatch要求 (Demand)
type DispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // 要求時刻
	Departure  *Point                 `protobuf:"bytes,2,opt,name=departure,proto3" json:"departure,omitempty"`                     // 乗車位置
	Arrival    *Point                 `protobuf:"bytes,4,opt,name=arrival,proto3" json:"arrival,omitempty"`                         // 降車位置
	TargetTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=target_time,json=targetTime,proto3" json:"target_time,omitempty"` // 目標乗車時刻
	Topic      string                 `protobuf:"bytes,7,opt,name=topic,proto3" json:"topic,omitempty"`                             // MQTT Topic
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DispatchRequest) GetDeparture() *Point {
	if x != nil {
		return x.Departure
	}
	return nil
}

func (x *DispatchRequest) GetArrival() *Point {
	if x != nil {
		return x.Arrival
	}
	return nil
}

func (x *DispatchRequest) GetTargetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TargetTime
	}
	return nil
}

func (x *DispatchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// Dispatch応答 (Supply)
type DispatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // 応答時刻
	Result        DispatchResponse_Result `protobuf:"varint,2,opt,name=result,proto3,enum=proto.alt_pt.DispatchResponse_Result" json:"result,omitempty"` // 配車結果
	AcceptNo      uint32                  `protobuf:"varint,3,opt,name=accept_no,json=acceptNo,proto3" json:"accept_no,omitempty"`                       // 受付番号
	DepartureTime *timestamppb.Timestamp  `protobuf:"bytes,6,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`         // 乗車時刻
	ArrivalTime   *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`               // 降車時刻
	Topic         string                  `protobuf:"bytes,8,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DispatchResponse) GetResult() DispatchResponse_Result {
	if x != nil {
		return x.Result
	}
	return DispatchResponse_SUCCESS
}

func (x *DispatchResponse) GetAcceptNo() uint32 {
	if x != nil {
		return x.AcceptNo
	}
	return 0
}

func (x *DispatchResponse) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *DispatchResponse) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *DispatchResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// 経路要求 (Demand)
type RouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // 要求時刻
	TaskId    []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // タスクID
	VehicleId uint32                 `protobuf:"varint,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"` // 車両ID
	Current   *Point                 `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`                       // 現在地
	LaneId    uint32                 `protobuf:"varint,5,opt,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`          // レーンID
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{5}
}

func (x *RouteRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RouteRequest) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *RouteRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *RouteRequest) GetCurrent() *Point {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *RouteRequest) GetLaneId() uint32 {
	if x != nil {
		return x.LaneId
	}
	return 0
}

// 経路応答 (Supply)
type RouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // 応答時刻
	TaskId      []byte                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`           // タスクID
	Destination *Point                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`               // 目的地
	Altitude    float64                `protobuf:"fixed64,4,opt,name=altitude,proto3" json:"altitude,omitempty"`                   // 高度
	LaneId      []uint32               `protobuf:"varint,5,rep,packed,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`   // レーンID (4 x 100)
	LinkId      []uint32               `protobuf:"varint,6,rep,packed,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`   // リンクID (4 x 100)
	Velocity    []float32              `protobuf:"fixed32,7,rep,packed,name=velocity,proto3" json:"velocity,omitempty"`            // 速度 (4 x 100)
	VehicleId   uint32                 `protobuf:"varint,8,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"` // 車両ID
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{6}
}

func (x *RouteResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RouteResponse) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *RouteResponse) GetDestination() *Point {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *RouteResponse) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *RouteResponse) GetLaneId() []uint32 {
	if x != nil {
		return x.LaneId
	}
	return nil
}

func (x *RouteResponse) GetLinkId() []uint32 {
	if x != nil {
		return x.LinkId
	}
	return nil
}

func (x *RouteResponse) GetVelocity() []float32 {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *RouteResponse) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

// 位置情報 (for 車両)
type VehicleStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp      `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                          // 要求時刻
	Status    VehicleStatusRequest_Status `protobuf:"varint,2,opt,name=status,proto3,enum=proto.alt_pt.VehicleStatusRequest_Status" json:"status,omitempty"` // 状態
	TaskId    []byte                      `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                  // タスクID
	VehicleId uint32                      `protobuf:"varint,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`                        // 車両ID
	Current   *Point                      `protobuf:"bytes,5,opt,name=current,proto3" json:"current,omitempty"`                                              // 現在地
	Velocity  float32                     `protobuf:"fixed32,6,opt,name=velocity,proto3" json:"velocity,omitempty"`                                          // 速度 (km/h)
	LaneId    uint32                      `protobuf:"varint,7,opt,name=lane_id,json=laneId,proto3" json:"lane_id,omitempty"`                                 // レーンID
	Angle     float32                     `protobuf:"fixed32,8,opt,name=angle,proto3" json:"angle,omitempty"`                                                // 角度 (CCW/East:0)
}

func (x *VehicleStatusRequest) Reset() {
	*x = VehicleStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatusRequest) ProtoMessage() {}

func (x *VehicleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatusRequest.ProtoReflect.Descriptor instead.
func (*VehicleStatusRequest) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{7}
}

func (x *VehicleStatusRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *VehicleStatusRequest) GetStatus() VehicleStatusRequest_Status {
	if x != nil {
		return x.Status
	}
	return VehicleStatusRequest_READY
}

func (x *VehicleStatusRequest) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *VehicleStatusRequest) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *VehicleStatusRequest) GetCurrent() *Point {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *VehicleStatusRequest) GetVelocity() float32 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

func (x *VehicleStatusRequest) GetLaneId() uint32 {
	if x != nil {
		return x.LaneId
	}
	return 0
}

func (x *VehicleStatusRequest) GetAngle() float32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

// 位置情報 (for ディスパッチャ)
type VehicleStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamppb.Timestamp       `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                           // 応答時刻
	TaskId    []byte                       `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                                   // タスクID
	Result    VehicleStatusResponse_Result `protobuf:"varint,3,opt,name=result,proto3,enum=proto.alt_pt.VehicleStatusResponse_Result" json:"result,omitempty"` // 結果
	VehicleId uint32                       `protobuf:"varint,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`                         // 車両ID
}

func (x *VehicleStatusResponse) Reset() {
	*x = VehicleStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alt_pt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VehicleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatusResponse) ProtoMessage() {}

func (x *VehicleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alt_pt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatusResponse.ProtoReflect.Descriptor instead.
func (*VehicleStatusResponse) Descriptor() ([]byte, []int) {
	return file_alt_pt_proto_rawDescGZIP(), []int{8}
}

func (x *VehicleStatusResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *VehicleStatusResponse) GetTaskId() []byte {
	if x != nil {
		return x.TaskId
	}
	return nil
}

func (x *VehicleStatusResponse) GetResult() VehicleStatusResponse_Result {
	if x != nil {
		return x.Result
	}
	return VehicleStatusResponse_COMPLETED
}

func (x *VehicleStatusResponse) GetVehicleId() uint32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

var File_alt_pt_proto protoreflect.FileDescriptor

var file_alt_pt_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a,
	0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x0e, 0x44,
	0x69, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x38, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c,
	0x74, 0x5f, 0x70, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x29,
	0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x32, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x52, 0x45, 0x41, 0x4b, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x49, 0x44, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x22, 0xb3, 0x01,
	0x0a, 0x12, 0x44, 0x69, 0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3f,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x2e, 0x44, 0x69,
	0x73, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x22, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52,
	0x45, 0x10, 0x01, 0x22, 0x80, 0x02, 0x0a, 0x0f, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x31, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74,
	0x5f, 0x70, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x64, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c,
	0x74, 0x5f, 0x70, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x12, 0x3b, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0xe4, 0x02, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c,
	0x74, 0x5f, 0x70, 0x74, 0x2e, 0x44, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x5f, 0x6e,
	0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4e,
	0x6f, 0x12, 0x41, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x22, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00,
	0x12, 0x0b, 0x0a, 0x07, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x01, 0x22, 0xc8, 0x01,
	0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x2d, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74,
	0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x64, 0x22, 0xa2, 0x02, 0x0a, 0x0d, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70,
	0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x06, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6b,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x07,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0xe7, 0x02,
	0x0a, 0x14, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x2e,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x07, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x2e, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65,
	0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x76, 0x65,
	0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x61, 0x6e, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05,
	0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x20, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55,
	0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x22, 0xf2, 0x01, 0x0a, 0x15, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x61,
	0x73, 0x6b, 0x49, 0x64, 0x12, 0x42, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x61, 0x6c, 0x74,
	0x5f, 0x70, 0x74, 0x2e, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x23, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x57, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x42, 0x21, 0x5a, 0x1f,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x65, 0x72,
	0x65, 0x78, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x61, 0x6c, 0x74, 0x5f, 0x70, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alt_pt_proto_rawDescOnce sync.Once
	file_alt_pt_proto_rawDescData = file_alt_pt_proto_rawDesc
)

func file_alt_pt_proto_rawDescGZIP() []byte {
	file_alt_pt_proto_rawDescOnce.Do(func() {
		file_alt_pt_proto_rawDescData = protoimpl.X.CompressGZIP(file_alt_pt_proto_rawDescData)
	})
	return file_alt_pt_proto_rawDescData
}

var file_alt_pt_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_alt_pt_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_alt_pt_proto_goTypes = []interface{}{
	(DisabilityInfo_Type)(0),          // 0: proto.alt_pt.DisabilityInfo.Type
	(DisabilityResponse_Result)(0),    // 1: proto.alt_pt.DisabilityResponse.Result
	(DispatchResponse_Result)(0),      // 2: proto.alt_pt.DispatchResponse.Result
	(VehicleStatusRequest_Status)(0),  // 3: proto.alt_pt.VehicleStatusRequest.Status
	(VehicleStatusResponse_Result)(0), // 4: proto.alt_pt.VehicleStatusResponse.Result
	(*Point)(nil),                     // 5: proto.alt_pt.Point
	(*DisabilityInfo)(nil),            // 6: proto.alt_pt.DisabilityInfo
	(*DisabilityResponse)(nil),        // 7: proto.alt_pt.DisabilityResponse
	(*DispatchRequest)(nil),           // 8: proto.alt_pt.DispatchRequest
	(*DispatchResponse)(nil),          // 9: proto.alt_pt.DispatchResponse
	(*RouteRequest)(nil),              // 10: proto.alt_pt.RouteRequest
	(*RouteResponse)(nil),             // 11: proto.alt_pt.RouteResponse
	(*VehicleStatusRequest)(nil),      // 12: proto.alt_pt.VehicleStatusRequest
	(*VehicleStatusResponse)(nil),     // 13: proto.alt_pt.VehicleStatusResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_alt_pt_proto_depIdxs = []int32{
	14, // 0: proto.alt_pt.DisabilityInfo.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.alt_pt.DisabilityInfo.type:type_name -> proto.alt_pt.DisabilityInfo.Type
	5,  // 2: proto.alt_pt.DisabilityInfo.point:type_name -> proto.alt_pt.Point
	14, // 3: proto.alt_pt.DisabilityResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: proto.alt_pt.DisabilityResponse.result:type_name -> proto.alt_pt.DisabilityResponse.Result
	14, // 5: proto.alt_pt.DispatchRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 6: proto.alt_pt.DispatchRequest.departure:type_name -> proto.alt_pt.Point
	5,  // 7: proto.alt_pt.DispatchRequest.arrival:type_name -> proto.alt_pt.Point
	14, // 8: proto.alt_pt.DispatchRequest.target_time:type_name -> google.protobuf.Timestamp
	14, // 9: proto.alt_pt.DispatchResponse.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 10: proto.alt_pt.DispatchResponse.result:type_name -> proto.alt_pt.DispatchResponse.Result
	14, // 11: proto.alt_pt.DispatchResponse.departure_time:type_name -> google.protobuf.Timestamp
	14, // 12: proto.alt_pt.DispatchResponse.arrival_time:type_name -> google.protobuf.Timestamp
	14, // 13: proto.alt_pt.RouteRequest.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 14: proto.alt_pt.RouteRequest.current:type_name -> proto.alt_pt.Point
	14, // 15: proto.alt_pt.RouteResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 16: proto.alt_pt.RouteResponse.destination:type_name -> proto.alt_pt.Point
	14, // 17: proto.alt_pt.VehicleStatusRequest.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 18: proto.alt_pt.VehicleStatusRequest.status:type_name -> proto.alt_pt.VehicleStatusRequest.Status
	5,  // 19: proto.alt_pt.VehicleStatusRequest.current:type_name -> proto.alt_pt.Point
	14, // 20: proto.alt_pt.VehicleStatusResponse.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 21: proto.alt_pt.VehicleStatusResponse.result:type_name -> proto.alt_pt.VehicleStatusResponse.Result
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_alt_pt_proto_init() }
func file_alt_pt_proto_init() {
	if File_alt_pt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alt_pt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisabilityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alt_pt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VehicleStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alt_pt_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alt_pt_proto_goTypes,
		DependencyIndexes: file_alt_pt_proto_depIdxs,
		EnumInfos:         file_alt_pt_proto_enumTypes,
		MessageInfos:      file_alt_pt_proto_msgTypes,
	}.Build()
	File_alt_pt_proto = out.File
	file_alt_pt_proto_rawDesc = nil
	file_alt_pt_proto_goTypes = nil
	file_alt_pt_proto_depIdxs = nil
}
