// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: delivery_planning.proto

package proto

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxVehicleUnit    uint64 `protobuf:"varint,1,opt,name=max_vehicle_unit,json=maxVehicleUnit,proto3" json:"max_vehicle_unit,omitempty"`
	StartDeliveryTime string `protobuf:"bytes,2,opt,name=start_delivery_time,json=startDeliveryTime,proto3" json:"start_delivery_time,omitempty"`
	EndDeliveryTime   string `protobuf:"bytes,3,opt,name=end_delivery_time,json=endDeliveryTime,proto3" json:"end_delivery_time,omitempty"`
}

func (x *TargetInfo) Reset() {
	*x = TargetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TargetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInfo) ProtoMessage() {}

func (x *TargetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetInfo.ProtoReflect.Descriptor instead.
func (*TargetInfo) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{0}
}

func (x *TargetInfo) GetMaxVehicleUnit() uint64 {
	if x != nil {
		return x.MaxVehicleUnit
	}
	return 0
}

func (x *TargetInfo) GetStartDeliveryTime() string {
	if x != nil {
		return x.StartDeliveryTime
	}
	return ""
}

func (x *TargetInfo) GetEndDeliveryTime() string {
	if x != nil {
		return x.EndDeliveryTime
	}
	return ""
}

type PackageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageId    uint64  `protobuf:"varint,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Latitude     float64 `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude    float64 `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Weight       uint64  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	DeliveryTime uint32  `protobuf:"varint,5,opt,name=delivery_time,json=deliveryTime,proto3" json:"delivery_time,omitempty"`
}

func (x *PackageInfo) Reset() {
	*x = PackageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageInfo) ProtoMessage() {}

func (x *PackageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageInfo.ProtoReflect.Descriptor instead.
func (*PackageInfo) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{1}
}

func (x *PackageInfo) GetPackageId() uint64 {
	if x != nil {
		return x.PackageId
	}
	return 0
}

func (x *PackageInfo) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PackageInfo) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PackageInfo) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PackageInfo) GetDeliveryTime() uint32 {
	if x != nil {
		return x.DeliveryTime
	}
	return 0
}

type DeliveryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeliveryId   uint64         `protobuf:"varint,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	PackagesInfo []*PackageInfo `protobuf:"bytes,2,rep,name=packages_info,json=packagesInfo,proto3" json:"packages_info,omitempty"`
}

func (x *DeliveryInfo) Reset() {
	*x = DeliveryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryInfo) ProtoMessage() {}

func (x *DeliveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryInfo.ProtoReflect.Descriptor instead.
func (*DeliveryInfo) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryInfo) GetDeliveryId() uint64 {
	if x != nil {
		return x.DeliveryId
	}
	return 0
}

func (x *DeliveryInfo) GetPackagesInfo() []*PackageInfo {
	if x != nil {
		return x.PackagesInfo
	}
	return nil
}

type DeliveryPlanningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId      uint32        `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimeStamp    string        `protobuf:"bytes,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	TargetInfo   *TargetInfo   `protobuf:"bytes,3,opt,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	DeliveryInfo *DeliveryInfo `protobuf:"bytes,4,opt,name=delivery_info,json=deliveryInfo,proto3" json:"delivery_info,omitempty"`
}

func (x *DeliveryPlanningRequest) Reset() {
	*x = DeliveryPlanningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryPlanningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPlanningRequest) ProtoMessage() {}

func (x *DeliveryPlanningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPlanningRequest.ProtoReflect.Descriptor instead.
func (*DeliveryPlanningRequest) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryPlanningRequest) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DeliveryPlanningRequest) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *DeliveryPlanningRequest) GetTargetInfo() *TargetInfo {
	if x != nil {
		return x.TargetInfo
	}
	return nil
}

func (x *DeliveryPlanningRequest) GetDeliveryInfo() *DeliveryInfo {
	if x != nil {
		return x.DeliveryInfo
	}
	return nil
}

type DeliveryPlanAdoption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId   uint32 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimeStamp string `protobuf:"bytes,2,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	ModuleId  uint64 `protobuf:"varint,3,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	ProvideId string `protobuf:"bytes,4,opt,name=provide_id,json=provideId,proto3" json:"provide_id,omitempty"`
}

func (x *DeliveryPlanAdoption) Reset() {
	*x = DeliveryPlanAdoption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryPlanAdoption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPlanAdoption) ProtoMessage() {}

func (x *DeliveryPlanAdoption) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPlanAdoption.ProtoReflect.Descriptor instead.
func (*DeliveryPlanAdoption) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryPlanAdoption) GetEventId() uint32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *DeliveryPlanAdoption) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *DeliveryPlanAdoption) GetModuleId() uint64 {
	if x != nil {
		return x.ModuleId
	}
	return 0
}

func (x *DeliveryPlanAdoption) GetProvideId() string {
	if x != nil {
		return x.ProvideId
	}
	return ""
}

type DeliveryPlanningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeliveryPlanningResponse) Reset() {
	*x = DeliveryPlanningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_delivery_planning_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeliveryPlanningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPlanningResponse) ProtoMessage() {}

func (x *DeliveryPlanningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_planning_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPlanningResponse.ProtoReflect.Descriptor instead.
func (*DeliveryPlanningResponse) Descriptor() ([]byte, []int) {
	return file_delivery_planning_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryPlanningResponse) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_delivery_planning_proto protoreflect.FileDescriptor

var file_delivery_planning_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x6e,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x70, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x6e,
	0x64, 0x5f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x6b, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0b,
	0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49, 0x64, 0x12, 0x3a, 0x0a,
	0x0d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xc7, 0x01, 0x0a, 0x17, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x35, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3b, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x50, 0x6c, 0x61, 0x6e, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x6f, 0x64, 0x75, 0x6c,
	0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c,
	0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x96, 0x02, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x82, 0x01, 0x0a, 0x13,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50,
	0x6c, 0x61, 0x6e, 0x12, 0x21, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1e, 0x22, 0x19, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x6c, 0x61,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x3a, 0x01, 0x2a,
	0x12, 0x7d, 0x0a, 0x12, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65,
	0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x12, 0x1e, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x41, 0x64,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x22, 0x2e, 0x64, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1d, 0x22, 0x18, 0x2f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x70, 0x6c, 0x61,
	0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x3a, 0x01, 0x2a, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6d,
	0x61, 0x72, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x65, 0x6c,
	0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_delivery_planning_proto_rawDescOnce sync.Once
	file_delivery_planning_proto_rawDescData = file_delivery_planning_proto_rawDesc
)

func file_delivery_planning_proto_rawDescGZIP() []byte {
	file_delivery_planning_proto_rawDescOnce.Do(func() {
		file_delivery_planning_proto_rawDescData = protoimpl.X.CompressGZIP(file_delivery_planning_proto_rawDescData)
	})
	return file_delivery_planning_proto_rawDescData
}

var file_delivery_planning_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_delivery_planning_proto_goTypes = []interface{}{
	(*TargetInfo)(nil),               // 0: dp_proto.TargetInfo
	(*PackageInfo)(nil),              // 1: dp_proto.PackageInfo
	(*DeliveryInfo)(nil),             // 2: dp_proto.DeliveryInfo
	(*DeliveryPlanningRequest)(nil),  // 3: dp_proto.DeliveryPlanningRequest
	(*DeliveryPlanAdoption)(nil),     // 4: dp_proto.DeliveryPlanAdoption
	(*DeliveryPlanningResponse)(nil), // 5: dp_proto.DeliveryPlanningResponse
}
var file_delivery_planning_proto_depIdxs = []int32{
	1, // 0: dp_proto.DeliveryInfo.packages_info:type_name -> dp_proto.PackageInfo
	0, // 1: dp_proto.DeliveryPlanningRequest.target_info:type_name -> dp_proto.TargetInfo
	2, // 2: dp_proto.DeliveryPlanningRequest.delivery_info:type_name -> dp_proto.DeliveryInfo
	3, // 3: dp_proto.DeliveryPlanning.RequestDeliveryPlan:input_type -> dp_proto.DeliveryPlanningRequest
	4, // 4: dp_proto.DeliveryPlanning.SelectDeliveryPlan:input_type -> dp_proto.DeliveryPlanAdoption
	5, // 5: dp_proto.DeliveryPlanning.RequestDeliveryPlan:output_type -> dp_proto.DeliveryPlanningResponse
	5, // 6: dp_proto.DeliveryPlanning.SelectDeliveryPlan:output_type -> dp_proto.DeliveryPlanningResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_delivery_planning_proto_init() }
func file_delivery_planning_proto_init() {
	if File_delivery_planning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_delivery_planning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TargetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_planning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_planning_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_planning_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryPlanningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_planning_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryPlanAdoption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_delivery_planning_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeliveryPlanningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_delivery_planning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_planning_proto_goTypes,
		DependencyIndexes: file_delivery_planning_proto_depIdxs,
		MessageInfos:      file_delivery_planning_proto_msgTypes,
	}.Build()
	File_delivery_planning_proto = out.File
	file_delivery_planning_proto_rawDesc = nil
	file_delivery_planning_proto_goTypes = nil
	file_delivery_planning_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DeliveryPlanningClient is the client API for DeliveryPlanning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DeliveryPlanningClient interface {
	RequestDeliveryPlan(ctx context.Context, in *DeliveryPlanningRequest, opts ...grpc.CallOption) (*DeliveryPlanningResponse, error)
	SelectDeliveryPlan(ctx context.Context, in *DeliveryPlanAdoption, opts ...grpc.CallOption) (*DeliveryPlanningResponse, error)
}

type deliveryPlanningClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryPlanningClient(cc grpc.ClientConnInterface) DeliveryPlanningClient {
	return &deliveryPlanningClient{cc}
}

func (c *deliveryPlanningClient) RequestDeliveryPlan(ctx context.Context, in *DeliveryPlanningRequest, opts ...grpc.CallOption) (*DeliveryPlanningResponse, error) {
	out := new(DeliveryPlanningResponse)
	err := c.cc.Invoke(ctx, "/dp_proto.DeliveryPlanning/RequestDeliveryPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryPlanningClient) SelectDeliveryPlan(ctx context.Context, in *DeliveryPlanAdoption, opts ...grpc.CallOption) (*DeliveryPlanningResponse, error) {
	out := new(DeliveryPlanningResponse)
	err := c.cc.Invoke(ctx, "/dp_proto.DeliveryPlanning/SelectDeliveryPlan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryPlanningServer is the server API for DeliveryPlanning service.
type DeliveryPlanningServer interface {
	RequestDeliveryPlan(context.Context, *DeliveryPlanningRequest) (*DeliveryPlanningResponse, error)
	SelectDeliveryPlan(context.Context, *DeliveryPlanAdoption) (*DeliveryPlanningResponse, error)
}

// UnimplementedDeliveryPlanningServer can be embedded to have forward compatible implementations.
type UnimplementedDeliveryPlanningServer struct {
}

func (*UnimplementedDeliveryPlanningServer) RequestDeliveryPlan(context.Context, *DeliveryPlanningRequest) (*DeliveryPlanningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDeliveryPlan not implemented")
}
func (*UnimplementedDeliveryPlanningServer) SelectDeliveryPlan(context.Context, *DeliveryPlanAdoption) (*DeliveryPlanningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectDeliveryPlan not implemented")
}

func RegisterDeliveryPlanningServer(s *grpc.Server, srv DeliveryPlanningServer) {
	s.RegisterService(&_DeliveryPlanning_serviceDesc, srv)
}

func _DeliveryPlanning_RequestDeliveryPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryPlanningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryPlanningServer).RequestDeliveryPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dp_proto.DeliveryPlanning/RequestDeliveryPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryPlanningServer).RequestDeliveryPlan(ctx, req.(*DeliveryPlanningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryPlanning_SelectDeliveryPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryPlanAdoption)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryPlanningServer).SelectDeliveryPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dp_proto.DeliveryPlanning/SelectDeliveryPlan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryPlanningServer).SelectDeliveryPlan(ctx, req.(*DeliveryPlanAdoption))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeliveryPlanning_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dp_proto.DeliveryPlanning",
	HandlerType: (*DeliveryPlanningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestDeliveryPlan",
			Handler:    _DeliveryPlanning_RequestDeliveryPlan_Handler,
		},
		{
			MethodName: "SelectDeliveryPlan",
			Handler:    _DeliveryPlanning_SelectDeliveryPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery_planning.proto",
}
